version: "3.3"
services:
  gateway:
    image: quay.io/hellofresh/janus
    ports:
      - "8080:8080"
      - "8084:8081"
    volumes:
      - ./janus.toml:/etc/janus/janus.toml
      - ./apis:/etc/janus/apis
      - ./auth:/etc/janus/auth
