server:
  port: 8080
jtweet:
  jwt:
    secret: "12345"
  services:
    tweet:
      endpoint: "http://tweetmanagement:8080"
    user:
      endpoint: "http://customermanagement:8080"
spring:
  cloud:
    gateway:
      routes:
      - id: user_management
        uri: http://customermanagement:8080/
        predicates:
          - Path=/v1/users/**